### ISSUE TITLE
one title for all of them

### ISSUE THREAD

**Issue by Grummfy** [ARCANEDEV/SEO-Helper#5]
Hello,
this lib seems great, but   we should have the possibility from a single setTitle (or any other common stuff)  with another like useGraph('OG',' twitter','...') to let the lib generated title for opengraph, twitter, and the other lib. This will reduce drastically the number of call to do to have all seo stuff.

thanks

**Comment by arcanedev-maroc** [comment]
Hi @Grummfy, thanks for using this package.

As you can see, the documentation is not completed because i'm still working on other stuff.

There is a class that group all the meta generators: [SeoHelper Class](https://github.com/ARCANEDEV/SEO-Helper/blob/master/src/SeoHelper.php).

For usage examples, check the tests folder : https://github.com/ARCANEDEV/SEO-Helper/blob/master/tests/SeoHelperTest.php

**Comment by Grummfy** [comment]
thanks
